server:
  error:
    include-stacktrace: never

spring:
  datasource:
    url: jdbc:mysql://us-cdbr-east-06.cleardb.net/heroku_7722a96e532a7cc?reconnect=true
    username: bbb6d732b7aba8
    password: 85a7ceb0

  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
